### ISSUE TITLE
Update error when attempting to 'Protect Branch'

### ISSUE THREAD

**Issue by aperiooculus** [gitbucket/gitbucket#1154]
When attempting to protect a branch I receive a modal warning from my browser stating "update error" (Please see image below). 
I am using gitbucket version  3.12, running in Apache Tomcat/7.0.68 with JVM Version 1.8.0_73-b02 on Windows Server 2012 R2.

![image](https://cloud.githubusercontent.com/assets/7217257/13815545/5e8f87f6-eb61-11e5-8856-7c449e6c34ef.png)

**Comment by takezoe** [comment]
This problem already fixed in #1140. Please wait for the next release.

**Comment by aperiooculus** [comment]
@takezoe Thanks!

**Comment by aperiooculus** [comment]
@takezoe I have just updated to version 3.13 and I am still receiving this error.

**Comment by aperiooculus** [comment]
Can we reopen this issue?

**Comment by takezoe** [comment]
@aperiooculus Sorry, I've overlooked. This problem is caused when GitBucket is not mapped to the document root of the¥ server. I fixed again and released in 3.14 and 4.0 (They are going to be released same day!)

**Comment by YunYunDetective** [comment]
I encounted same bug at gitbucket 4.0 with PostgreSQL.
